version: '3'
services:
  jupyter:
    image: dolfinx/lab
    ports:
      - "8888:8888"
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
  certbot:
    image: certbot/certbot
